# Generated by Django 3.0.6 on 2020-05-16 12:49

from django.db import migrations, models
import django.db.models.deletion
import school_affair.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('begin_time', school_affair.field.YMField(max_length=7)),
                ('grade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_teacher',
            fields=[
                ('id_number', models.IntegerField(primary_key=True, serialize=False)),
                ('name_chinese', models.CharField(max_length=45)),
                ('born_date', school_affair.field.BirthField()),
                ('nationality', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('student_teacher_id', models.CharField(max_length=45, unique=True)),
                ('entry_data', school_affair.field.YMField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Student_unnormal_change',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', school_affair.field.YMField(max_length=7)),
                ('class_after', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='after', to='school_affair.Class')),
                ('class_before', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='before', to='school_affair.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', school_affair.field.BirthField()),
            ],
        ),
        migrations.CreateModel(
            name='Grade_downward',
            fields=[
                ('student_unnormal_change_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='school_affair.Student_unnormal_change')),
            ],
        ),
        migrations.CreateModel(
            name='Major_transfer',
            fields=[
                ('student_unnormal_change_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='school_affair.Student_unnormal_change')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_teacher_idnumber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='school_affair.Student_teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('campus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_affair.Campus')),
            ],
        ),
        migrations.CreateModel(
            name='Home_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_address', models.CharField(max_length=45)),
                ('post_code', models.CharField(max_length=45)),
                ('home_telephone_number', models.CharField(max_length=45)),
                ('setudent_teacher_id_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_affair.Student_teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('start_year', models.IntegerField()),
                ('course_time', models.CharField(max_length=45)),
                ('major_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_affair.Major')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='major_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_affair.Major'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('student_teacher_idnumber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='school_affair.Student_teacher')),
                ('major_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_affair.Major')),
            ],
        ),
        migrations.AddField(
            model_name='student_unnormal_change',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_affair.Student'),
        ),
        migrations.AddField(
            model_name='student',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_affair.Class'),
        ),
        migrations.AddField(
            model_name='major',
            name='person_in_cahrge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_affair.Teacher'),
        ),
        migrations.CreateModel(
            name='Course_sign_up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_affair.Course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_affair.Student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_affair.Teacher'),
        ),
        migrations.AddField(
            model_name='class',
            name='header_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_affair.Teacher'),
        ),
        migrations.AddConstraint(
            model_name='course_sign_up',
            constraint=models.UniqueConstraint(fields=('course_id', 'student_id'), name='no duplicated sign-up'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(check=models.Q(start_year__gte=1960), name='past'),
        ),
    ]
