# Generated by Django 3.0.6 on 2020-05-16 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_affair', '0002_auto_20200516_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade_downward',
            name='id',
        ),
        migrations.AlterField(
            model_name='grade_downward',
            name='student_unnormal_change_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='school_affair.Student_unnormal_change'),
        ),
        migrations.AlterField(
            model_name='major_transfer',
            name='student_unnormal_change_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='school_affair.Student_unnormal_change'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_teacher_idnumber',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='school_affair.Student_teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='student_teacher_idnumber',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='school_affair.Student_teacher'),
        ),
    ]
