# Generated by Django 3.0.6 on 2020-05-19 00:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_affair', '0002_auto_20200518_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_information',
            name='home_address',
            field=models.CharField(blank=True, max_length=45, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='home_information',
            name='home_telephone_number',
            field=models.CharField(blank=True, max_length=45, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='home_information',
            name='post_code',
            field=models.CharField(blank=True, max_length=45, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
