# Generated by Django 3.0.6 on 2020-05-19 23:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_affair', '0003_auto_20200519_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='major',
            old_name='person_in_cahrge',
            new_name='person_in_charge',
        ),
        migrations.AlterField(
            model_name='student_unnormal_change',
            name='id',
            field=models.CharField(max_length=45, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
