# Generated by Django 3.0.6 on 2020-05-16 10:10

from django.db import migrations, models
import school_affair.field


class Migration(migrations.Migration):

    dependencies = [
        ('school_affair', '0004_auto_20200516_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', school_affair.field.YMField(max_length=7)),
            ],
        ),
    ]
